#!/usr/bin/env bash

dotfiles_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"

if ! [[ -d ~/.config ]]; then
  mkdir ~/.config
fi

# Fish
ln -s $dotfiles_dir/fish/ ~/.config/fish

# Git
ln -s $dotfiles_dir/git/ ~/.config/git

# Vim
ln -s $dotfiles_dir/vim/ ~/.vim
mkdir ~/.vim/tmp

# Ruby
ln -s $dotfiles_dir/ruby-version ~/.ruby-version
ln -s $dotfiles_dir/scripts/ruby-test /usr/local/bin/ruby-test
