;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-append
        evil-append-line
        evil-backward-char
        evil-change-whole-line
        evil-delete
        evil-delete-backward-char-and-join
        evil-delete-char
        evil-exit-emacs-state
        evil-forward-char
        evil-insert
        evil-next-line
        evil-normal-state
        evil-previous-line
        evil-substitute
        keyboard-quit
        smex
        sp--self-insert-command
        sp-add-to-previous-sexp
        sp-kill-sexp
        sp-splice-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        end-of-buffer
        ))
