;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-append
        evil-backward-char
        evil-delete
        evil-delete-char
        evil-exit-emacs-state
        evil-forward-char
        evil-insert
        evil-next-line
        evil-normal-state
        evil-previous-line
        evil-substitute
        keyboard-quit
        smex
        sp-kill-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        ))
